#import "template.typ": *
#import "macros.typ": *
#import "@preview/xarrow:0.3.1": xarrow
#import "@preview/fletcher:0.4.5" as fletcher: diagram, node, edge

#show: project.with(
  title: "Measure Theory Cheat Sheet",
  authors: (
    (name: "Niels Slotboom", email: "slotboom.n@gmail.com"),
  ),
)

#outline(indent:auto)


= $sigma$-Algebras, Measurable Spaces and Measure Spaces
In the following, $X$ denotes a set and $P(X)$ its power set.
\ \
*Definition* ($sigma$-Algebra) A family of sets $cal(A) subset P(X)$ is called $sigma$-Algebra if

+ $nothing,X in cal(A)$,

+ $A in cal(A) => A^c = X without A in cal(A)$,
+ $A_n in cal(A)$, $n in NN$ $=>$ $union.big_(n in NN) A_n in cal(A)$.

In particular, a subset $A in cal(A)$ of $X$ is called _measurable_. The pair $(X,cal(A))$ is called a _measurable space_.
\ \
*Examples* (of $sigma$-Algebras)
+ $cal(A) = {nothing, X}$ is the smallest $sigma$-algebra one can define. 
+ $cal(A) = P(X)$ is the largest.

*Remark* It is easy to show that if $cal(A)_i$ are $sigma$-algebras for all $i in I$ where $I$ is some index set, that
$
  cal(A) := sect.big_(i in I) cal(A)_i
$
is a $sigma$-algebra as well.
\ \
*Definition* (Generated $sigma$-Algebra) Let $M subset P(X)$ be some family of subsets of $X$. Then, we define
$
  sigma(M) := sect.big_(cal(A) med sigma-"alg.",\ cal(A) supset M) #h(-.5em)cal(A)
$
This is the smallest $sigma$-algebra containing $M$.
\ \
*Definition* (Borel $sigma$-algebra) Let $(X,tau)$ be a topological space. The $sigma$-algebra defined by
$
  B(X) = sigma(tau),
$
i.e., the $sigma$-algebra generated by the open sets, is termed the _Borel_ $sigma$-algebra. In particular, it contains all open and closed sets.
\ \
*Definition* (Measure) Let $(X,cal(A))$ be a measurable space. A map $mu : cal(A) -> [0,infty]$ is called a _measure_ if

+ $mu(nothing) = 0$,
+ It satisfies $sigma$-additivity, that is
  $
    mu(union.big_(i = 1)^infty A_i)  =sum_(i=1)^infty mu(A_i)
  $
  where $A_i in cal(A)$, $i in NN$ such that $A_i sect A_j = nothing$, $i != j$. 

The triple $(X,A,mu)$ is called a _measure space_. The calculation rules for infinite measure, $mu(A) = infty$, are as follows:
$
  x + infty &:= infty, quad x in [0, infty],\
  x dot infty &:= infty, quad x in (0,infty],\
  0 dot infty &:= 0.
$
\ \
*Examples* Let $(X, cal(A))$ be a measurable space. For any such choice there exists
+ the _Counting Measure_: 
  $
    mu(A) := cases(|A|\,quad& A "finite"\,,infty\, quad& A "infinite". ), quad A in cal(A)
  $

+ the _Dirac measure_: Choose $p in X$. Then for any $A in cal(A)$ define
  $
    delta_p (A) := cases(1\,quad&p in A\,\ 0\,quad&p in.not A.)
  $

= Measurable Maps
*Definition* (Measurable Function)
Let $(X,cal(A))$ and $(Y, cal(B))$ be measurable spaces. A function $f:X->Y$ is called _measurable_ if for each $B in cal(B)$, 
$
  f^(-1) (B) in cal(A).    
$
*Example* The characteristic function of a set $A in cal(A)$, defined by
$
  chi_A : X->RR, quad chi_A (x) = cases(1\,quad &x in A\,,0\,quad&x in.not A,)
$
is a measurable function. 
\ \ 
*Lemma* Let $(X,B(X))$, $(Y, B(Y))$ be measurable spaces equipped with Borel $sigma$-algebras. Then, 
$
  f:X->Y "continuous" quad ==> quad f "measurable".
$
_Proof._ Note that the preimage commutes with unions and complements,
$
  f^(-1)(union.big B_i) = union.big f^(-1) (B_i) quad "and" quad f^(-1)(B^c) = (f^(-1)(B))^c.
$
Since all elements in the Borel $sigma$-algebras $B(X), B(Y)$ can be written
using countable unions and complements of open sets, it is sufficient to show that $f^(-1)(B)$ is open for any $B subset Y$ open. This however holds trivially by the definition of continuity. #qed
\ \
*Lemma* Let $(X,cal(A))$, $(Y,cal(B))$ and $(Z,cal(C))$ be measurable spaces and $f:X->Y$ as well as $g:Y->Z$ measurable functions. Then, $g compose f$ is measurable.

_Proof._ Let $C in cal(C)$. Then,
  $
    (g compose f)^(-1)(C) = f^(-1)lr((underbrace(g^(-1)(C),in cal(B))),size:#30%) in cal(A),
  $
  due to measurability of $f$ and $g$.#qed
\ \
*Lemma* Let $f,g : X->RR^n$ be measurable with $(X,cal(A))$ and $(RR^n, B(RR^n))$ are measurable spaces. Then, $f+g$ is measurable#footnote[In analogy, the same result can be shown for $f-g$, or if $n=1$, for $f dot g$].

_Proof._ Define $phi:RR^n times RR^n -> RR^n$, $phi(x,y) = x+y$. This function is continuous and hence measurable. Moreover, define $F : X -> RR^n$, $F(x) = (f(x),g(x))$, which is also a measurable map. Then,
$
  f + g = phi compose F,
$
is measurable as a composition of measurable functions.#qed

= The Lebesgue Integral w.r.t. $mu$
